spring:
  security:
    user:
      name: admin
      password: admin
  application:
    name: blog
  freemarker:
    cache: false
  redis:
    cluster:
      # 各 Redis 节点信息
      nodes: 106.13.53.40:7001,106.13.53.40:7002,106.13.53.40:7003,106.13.53.40:7004,106.13.53.40:7005,106.13.53.40:7006
      # 执行命令超时时间
      command-timeout: 15000
      # 重试次数
      max-attempts: 5
      # 跨集群执行命令时要遵循的最大重定向数量
      max-redirects: 3
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 16
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
      # 是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
      test-on-borrow: true
      # 密码
      password: 7001

server:
  port: 8099
  servlet:
    context-path: /blog

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:17174/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@localhost:17173/eureka/
    #   表示eureka client间隔多久去拉取服务注册信息，默认为30秒，对于api-gateway，如果要迅速获取服务注册状态，可以缩小该值，比如5秒
    registry-fetch-interval-seconds: 5
    instance-info-replication-interval-seconds: 5
    #   是否将自己注册到eureka
    register-with-eureka: true
    #   是否需要去检索搜寻服务
    fetch-registry: true

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml

#log4j2
logging:
  config: classpath:log4j2.xml

ribbon:
  eager-load:
    enabled: true

feign:
  hystrix:
    enabled: false

## hihari连接池
hihari:
  primary:
    jdbcUrl: jdbc:mysql://106.13.53.40:3306/solo?serverTimezone=GMT&useUnicode=true&characterEncoding=utf-8
    username: martin
    password: Dxx3690.0
    driverClassName: com.mysql.cj.jdbc.Driver
    poolName: martinyuyy_hihari