server:
  port: 8099
  servlet:
    context-path: /blog
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.13.53.40:3306/test?serverTimezone=GMT&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  freemarker:
    cache: false
  redis:
    cluster:
      # 各 Redis 节点信息
      nodes: 106.13.53.40:7001,106.13.53.40:7002,106.13.53.40:7003,106.13.53.40:7004,106.13.53.40:7005,106.13.53.40:7006
      # 执行命令超时时间
      command-timeout: 15000
      # 重试次数
      max-attempts: 5
      # 跨集群执行命令时要遵循的最大重定向数量
      max-redirects: 3
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 16
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
      # 是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
      test-on-borrow: true
      # 密码
      password: 7001

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml

# 日志打印
logging:
  level:
    com:
      example:
        mapper: info
    org:
      springframework:
        web:
          client: info`